site_name: restframework-rdf
repo_url: https://github.com/UUDigitalHumanitieslab/restframework-rdf
plugins:
  - mkdocstrings
nav:
  - 'index.md'
  - 'getting-started.md'
  - API reference:
    - 'migrations.md'
    - 'namespaces.md'
    - 'parsers.md'
    - 'views.md'